BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[rcv_form] (
    [id] INT NOT NULL IDENTITY(1,1),
    [email] NVARCHAR(1000) NOT NULL,
    [item] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [rcv_form_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [rcv_form_email_key] UNIQUE NONCLUSTERED ([email])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
