ARG NODE_VERSION
FROM node:${NODE_VERSION}

WORKDIR /srv

RUN apt-get update && apt-get install -y openssl
RUN yarn global add pm2
RUN pm2 install pm2-logrotate
RUN pm2 set pm2-logrotate:max_size 10K

# CMD [ "pm2", "start" ]
ENTRYPOINT [ "pm2-runtime", "start", "ecosystem.config.js" ]
# CMD ["sh", "-c", "while true; do sleep 1; done"]
